; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v2.1.4 on Thu Dec 26 2019 17:05:22 GMT-0600 (Central Standard Time)
M400
M913 X40 Y40
G1 H1 X-800 F12000 ; move quickly to X axis endstop and stop there (first pass)
G1 X-10 F3600       ; go back a few mm
G1 H1 X-627 F360  ; move slowly to X axis endstop once more (second pass)
M400
M913 X100 Y100

